apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-api
  labels:
    app: notes-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-api
  template:
    metadata:
      labels:
        app: notes-api
    spec:
      containers:
        - name: notes-api
          image: najkhan1/personal:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: sql-url
            - secretRef:
                name: sql-creds-user
          volumeMounts:
            - name: sql-creds-user-vol
              mountPath: /var/sql-creds
            - name: sql-url-vol
              mountPath: /val/sql-creds
      volumes:
        - name: sql-creds-user-vol
          secret:
            secretName: sql-creds-user
        - name: sql-url-vol
          configMap:
            name: sql-url
